import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs'
import { auth } from '@clerk/nextjs/server';
import "./globals.css";
import { redirect } from "next/navigation";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { userId } = auth();
  auth().protect();
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`w-screen h-screen bg-gradient-to-tr from-black to-black/75 ${nunito.className}`}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
